name: Deploy website on push
on:
  push:
    branches: [ftp]
  pull_request:
    branches: [ftp]
  workflow_dispatch:
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        port: ${{ secrets.FTP_PORT }}
        protocol: ftps
        exclude: .git* .workflows* vendor* .env
        local-dir: build